services:
  frontend:
    image: bholechature/chiasm-frontend:1.1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chiasm-frontend
    environment:
      - NODE_ENV=${APP_ENV:-development}
    ports:
      - "3002:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - chiasm-network

  backend:
    image: bholechature/chiasm-backend:1.1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chiasm-backend
    ports:
      - "5001:5000"
    restart: unless-stopped
    networks:
      - chiasm-network

networks:   
  chiasm-network:
    driver: bridge
